#!/bin/bash
#postinst script for newscoop

set -e

. /usr/share/debconf/confmodule

#dbc_generate_include='php:/etc/newscoop/dbconfig.php'
#dbc_generate_include_owner='root:www-data'
#dbc_generate_include_perms='640'
#dbc_pgsql_createdb_encoding='UTF8'
#. /usr/share/dbconfig-common/dpkg/postinst
#dbc_go newscoop

if [ "$DPKG_DEBUG" = "developer" ]; then
    set -x
fi

WEB_USER=www-data
WEB_GROUP=www-data

package_name="newscoop"
datadir="/var/lib/${package_name}"
configdir="/etc/newscoop/4.3"
includefile="${configdir}/apache.conf"
a2tplfile="${configdir}/apache.vhost.tpl"
crontplfile="${configdir}/newscoop.cron.tpl"
cronincfile="${configdir}/newscoop.cron"
phpinifile="${configdir}/newscoop.ini"
TIMEZONE="$(cat /etc/timezone)"
OLDVERSION="$2"

case "$1" in
  configure|reconfigure)

    #webserver=`echo $webserver|sed -e 's/,  */ /g'`
    webserver="apache2"
    php="php5"
    dohtaccess=""

    # get the major/minor version of Apache installed locally
    APACHEVERSION=$(dpkg-query -f '${Version}' -W 'apache2' | cut -c 1-3)

    # tweak access settings if Apache 2.4 is installed
    if [ "$APACHEVERSION" = "2.4" ] ; then
      echo "Apache 2.4 detected, adjusting access configuration..."
      sed -i "s/#Require all granted/Require all granted/" ${includefile} ${a2tplfile}
    fi

    #  clean up previous configurations
    if [ -L /etc/$webserver/conf.d/newscoop.conf ]; then
      rm -f /etc/$webserver/conf.d/newscoop.conf || true
      restart="$webserver $restart"
    fi

    if [ -f /etc/$webserver/sites-available/newscoop-vhost ]; then
      a2dissite newscoop-vhost
    elif [ -f /etc/$webserver/sites-available/newscoop-vhost.conf ]; then
      a2dissite newscoop-vhost.conf
    fi

    if [ -L /etc/cron.d/newscoop ]; then
      rm -f /etc/cron.d/newscoop || true
    fi

    # Install new Apache configuration
    db_get newscoop/apache-setup
    if [ "$RET" == "system-wide (all vhosts)" ]; then
      if [ ! -d /etc/$webserver/conf.d/ ]; then
        install -d -m755 /etc/$webserver/conf.d/
      fi
      if [ ! -e /etc/$webserver/conf.d/newscoop.conf ]; then
        ln -s ${includefile} /etc/$webserver/conf.d/newscoop.conf
        a2enmod rewrite
        restart="$webserver $restart"
      fi
      dohtaccess="/newscoop"

    elif [ "$RET" == "dedicated v-host" ]; then
      db_get newscoop/apache-servername
      SN=$RET
      db_get newscoop/apache-serveradmin
      SA=$RET

      if [ ! -d /etc/$webserver/sites-available/ ]; then
        install -d -m755 /etc/$webserver/sites-available/
      fi

      sed -i "s/__SERVER_ADMIN__/${SA}/" ${a2tplfile}
      sed -i "s/__SERVER_NAME__/${SN}/" ${a2tplfile}
      cp ${a2tplfile} /etc/$webserver/sites-available/newscoop-vhost.conf
      a2ensite newscoop-vhost.conf
      a2enmod rewrite
      restart="$webserver $restart"
      dohtaccess="/"
    fi

    echo "Beginning PHP configuration..."
    sed -i "s:__TIME_ZONE__:${TIMEZONE}:" ${phpinifile}

    if [ ! -d /etc/$php/conf.d/ ]; then
      install -d -m755 /etc/$php/conf.d/
    fi

    if [ ! -e /etc/$php/conf.d/newscoop.ini ]; then
      ln -s ${phpinifile} /etc/$php/conf.d/newscoop.ini
      restart="$webserver $restart"
    fi

    echo "Setting up .htaccess file..."
    echo -ne "/RewriteBase/d\nwq\n\n" \
    | ed /var/lib/newscoop/.htaccess &>/dev/null || true

    if [ -n "${dohtaccess}" ]; then
      echo -ne "/RewriteEngine/\n+1i\n    RewriteBase ${dohtaccess}\n.\nwq\n" \
      | ed /var/lib/newscoop/.htaccess &>/dev/null || true
    fi

# for now - use NS's installer to set up the cron-jobs
# note: the NS installer won't purge these on uninstallation!
#   # CRON JOB
#   db_get newscoop/cronjob
#   if [ "$RET" == "true" ]; then
#     CU=www-data
#     CE=root@localhost
#     sed -e "s/__CRON_EMAIL__/${CE}/;s/__WWW_USER__/${CU}/" \
#       ${crontplfile} > ${cronincfile}
#     if [ ! -d /etc/cron.d/ ]; then
#       install -d -m755 /etc/cron.d/
#     fi
#     if [ ! -e /etc/cron.d/newscoop ]; then
#       ln -s ${cronincfile} /etc/cron.d/newscoop
#     fi
#   fi

    echo "Setting permissions..."
    dpkg-statoverride --list $datadir &>/dev/null || \
    dpkg-statoverride --add --force --update $WEB_USER $WEB_GROUP 0755 $datadir

    dpkg-statoverride --list $datadir/backup &>/dev/null || \
    dpkg-statoverride --add --force --update $WEB_USER $WEB_GROUP 0750 $datadir/backup

    dpkg-statoverride --list $datadir/cache &>/dev/null || \
    dpkg-statoverride --add --force --update $WEB_USER $WEB_GROUP 0755 $datadir/cache

    dpkg-statoverride --list $datadir/conf &>/dev/null || \
    dpkg-statoverride --add --force --update $WEB_USER $WEB_GROUP 0750 $datadir/conf

    dpkg-statoverride --list $datadir/images &>/dev/null || \
    dpkg-statoverride --add --force --update $WEB_USER $WEB_GROUP 0755 $datadir/images

    dpkg-statoverride --list $datadir/images/thumbnails &>/dev/null || \
    dpkg-statoverride --add --force --update $WEB_USER $WEB_GROUP 0755 $datadir/images/thumbnails

    dpkg-statoverride --list $datadir/install/cron_jobs &>/dev/null || \
    dpkg-statoverride --add --force --update $WEB_USER $WEB_GROUP 0750 $datadir/install/cron_jobs

    dpkg-statoverride --list $datadir/library/Proxy &>/dev/null || \
    dpkg-statoverride --add --force --update $WEB_USER $WEB_GROUP 0750 $datadir/library/Proxy

    dpkg-statoverride --list $datadir/log &>/dev/null || \
    dpkg-statoverride --add --force --update $WEB_USER $WEB_GROUP 0750 $datadir/log

    dpkg-statoverride --list $datadir/plugins &>/dev/null || \
    dpkg-statoverride --add --force --update $WEB_USER $WEB_GROUP 0750 $datadir/plugins

    dpkg-statoverride --list $datadir/public/bundles &>/dev/null || \
    dpkg-statoverride --add --force --update $WEB_USER $WEB_GROUP 0755 $datadir/public/bundles

    dpkg-statoverride --list $datadir/public/files &>/dev/null || \
    dpkg-statoverride --add --force --update $WEB_USER $WEB_GROUP 0755 $datadir/public/files

    dpkg-statoverride --list $datadir/public/pdf &>/dev/null || \
    dpkg-statoverride --add --force --update $WEB_USER $WEB_GROUP 0755 $datadir/public/pdf

    dpkg-statoverride --list $datadir/public/videos &>/dev/null || \
    dpkg-statoverride --add --force --update $WEB_USER $WEB_GROUP 0755 $datadir/public/videos

    dpkg-statoverride --list $datadir/themes &>/dev/null || \
    dpkg-statoverride --add --force --update $WEB_USER $WEB_GROUP 0750 $datadir/themes

    dpkg-statoverride --list $datadir/.htaccess &>/dev/null || \
    dpkg-statoverride --add --force --update $WEB_USER $WEB_GROUP 0644 $datadir/.htaccess

    # Installer needs to own all theme files, not just the themes directory
    chown -R $WEB_USER.$WEB_GROUP $datadir/themes/ || true

# newscoop-3.5 does not yet support that
#   # database setup
#   db_get newscoop/dbsetup
#   if [ -f /usr/share/dbconfig-common/dpkg/config -a "$RET" == "true" ]; then
#       echo "setting up database.. " >&2
#       dbc_dbtypes="mysql"
#       dbc_dbname=newscoop
#       dbc_dbuser=newscoop
#
#       # source dbconfig-common stuff
#       . /usr/share/dbconfig-common/dpkg/config --debconf-ok
#       dbc_go newscoop $@
#
#       # TODO: save db-account to newscoop-config.
#   fi

    # symlinks for sample data package

    if [ ! -h /var/lib/newscoop/install/sample_data/files ] && [ -d /usr/share/newscoop-sample-data/files/ ]; then
       ln -s /usr/share/newscoop-sample-data/files/ /var/lib/newscoop/install/sample_data/files
    fi

    if [ ! -h /var/lib/newscoop/install/sample_data/images ] && [ -d /usr/share/newscoop-sample-data/images/ ]; then
       ln -s /usr/share/newscoop-sample-data/images/ /var/lib/newscoop/install/sample_data/images
    fi

    if [ ! -h /var/lib/newscoop/install/sql/campsite_demo_data.sql ] && [ -e /usr/share/newscoop-sample-data/sql/campsite_demo_data.sql ]; then
       ln -s /usr/share/newscoop-sample-data/sql/campsite_demo_data.sql /var/lib/newscoop/install/sql/campsite_demo_data.sql
    fi

    if [ ! -h /var/lib/newscoop/install/sql/campsite_demo_prepare.sql ] && [ -e /usr/share/newscoop-sample-data/sql/campsite_demo_prepare.sql ]; then
       ln -s /usr/share/newscoop-sample-data/sql/campsite_demo_prepare.sql /var/lib/newscoop/install/sql/campsite_demo_prepare.sql
    fi

    if [ ! -h /var/lib/newscoop/install/sql/campsite_demo_tables.sql ] && [ -e /usr/share/newscoop-sample-data/sql/campsite_demo_tables.sql ]; then
       ln -s /usr/share/newscoop-sample-data/sql/campsite_demo_tables.sql /var/lib/newscoop/install/sql/campsite_demo_tables.sql
    fi

    # symlinks for geonames.org data package

    if [ ! -h /var/lib/newscoop/install/sql/CityLocations.csv ] && [ -e /usr/share/geonames-city-data/CityLocations.csv ]; then
       ln -s /usr/share/geonames-city-data/CityLocations.csv /var/lib/newscoop/install/sql/CityLocations.csv
    fi

    if [ ! -h /var/lib/newscoop/install/sql/CityNames.csv ] && [ -e /usr/share/geonames-city-data/CityNames.csv ]; then
       ln -s /usr/share/geonames-city-data/CityNames.csv /var/lib/newscoop/install/sql/CityNames.csv
    fi

    servers="apache2"
    . /usr/share/wwwconfig-common/restart.sh
    echo $error >&2

    if [ -n "${SN}" ]; then
     echo "Please open a browser at http://${SN}/ to complete Newscoop installation."
    fi

    db_stop

  ;;

  abort-upgrade|abort-remove|abort-deconfigure)

  ;;

  *)
       echo "postinst called with unknown argument \`$1'" >&2
       exit 1
  ;;
esac

#DEBHELPER#

exit 0
